import {
  Blocks,
  Braces,
  Cloud,
  Code2,
  Database,
  GitBranch,
  Globe2,
  Layers3,
  Network,
  Palette,
  ShieldCheck,
  TestTube2,
  type LucideIcon,
} from "lucide-react";

export type Project = {
  id: number;
  title: string;
  description: string;
  stack: string;
  level: string;
  progress: number;
  icon: LucideIcon;
  accent: string;
  topics: string[];
};

export const projects: Project[] = [
  {
    id: 1,
    title: "Адаптивная визитка",
    description: "Сверстай 3–5 экранов по макету для личного портфолио.",
    stack: "HTML · CSS",
    level: "Начальный",
    progress: 100,
    icon: Globe2,
    accent: "emerald",
    topics: ["Семантика", "Flexbox и Grid", "Адаптивность"],
  },
  {
    id: 2,
    title: "Todo-лист с API",
    description: "Создай todo-приложение с запросами, фильтрами и сохранением настроек.",
    stack: "JavaScript · REST API",
    level: "Начальный",
    progress: 64,
    icon: Braces,
    accent: "blue",
    topics: ["Async/await", "DOM и события", "LocalStorage"],
  },
  {
    id: 3,
    title: "Командный workflow",
    description: "Подготовь репозиторий, настрой ветки и пройди сценарий code review.",
    stack: "Git · GitHub · DevTools",
    level: "Начальный",
    progress: 0,
    icon: GitBranch,
    accent: "slate",
    topics: ["Ветки", "Коммиты", "Pull request"],
  },
  {
    id: 4,
    title: "Типизированный каталог",
    description: "Перепиши каталог данных на TypeScript с типизированным API.",
    stack: "TypeScript · REST API",
    level: "Начальный",
    progress: 0,
    icon: Code2,
    accent: "violet",
    topics: ["Generics", "Narrowing", "API-типы"],
  },
  {
    id: 5,
    title: "Каталог с фильтрами",
    description: "Создай приложение из компонентов с поиском и фильтрацией данных.",
    stack: "React · TypeScript",
    level: "Средний",
    progress: 0,
    icon: Blocks,
    accent: "cyan",
    topics: ["Компоненты", "Props и state", "Хуки"],
  },
  {
    id: 6,
    title: "Рабочее пространство",
    description: "Собери multi-view приложение с общим состоянием и переиспользуемыми блоками.",
    stack: "React · Zustand · Vite",
    level: "Средний",
    progress: 0,
    icon: Layers3,
    accent: "indigo",
    topics: ["Хуки", "Context", "Zustand"],
  },
  {
    id: 7,
    title: "Панель задач команды",
    description: "Сделай CRUD-доску задач с кешированием и валидацией формы.",
    stack: "React · TanStack Query · Zod",
    level: "Средний",
    progress: 0,
    icon: Database,
    accent: "amber",
    topics: ["REST", "Кеширование", "Формы"],
  },
  {
    id: 8,
    title: "Личный кабинет",
    description: "Создай кабинет с защищёнными маршрутами, ролями и профилем пользователя.",
    stack: "React Router · JWT",
    level: "Средний",
    progress: 0,
    icon: Network,
    accent: "rose",
    topics: ["Маршруты", "Авторизация", "Роли"],
  },
  {
    id: 9,
    title: "UI-kit продукта",
    description: "Собери небольшую дизайн-систему и задокументируй компоненты.",
    stack: "Tailwind · shadcn/ui · Storybook",
    level: "Средний",
    progress: 0,
    icon: Palette,
    accent: "pink",
    topics: ["Компоненты", "Storybook", "Состояния"],
  },
  {
    id: 10,
    title: "Контентная платформа",
    description: "Собери Next.js-приложение с несколькими типами рендеринга.",
    stack: "Next.js · TypeScript",
    level: "Продвинутый",
    progress: 0,
    icon: Cloud,
    accent: "sky",
    topics: ["App Router", "SSR и SSG", "Vercel"],
  },
  {
    id: 11,
    title: "Надёжный checkout",
    description: "Покрой тестами критичный сценарий оформления заказа и улучши Lighthouse.",
    stack: "Vitest · RTL · Playwright",
    level: "Продвинутый",
    progress: 0,
    icon: TestTube2,
    accent: "green",
    topics: ["Unit-тесты", "E2E", "Lighthouse"],
  },
  {
    id: 12,
    title: "Production-ready приложение",
    description: "Подготовь приложение к CI/CD, добавь security checklist и документацию.",
    stack: "GitHub Actions · Docker · Security",
    level: "Продвинутый",
    progress: 0,
    icon: ShieldCheck,
    accent: "orange",
    topics: ["CORS и CSP", "CI/CD", "Docker"],
  },
];
